baseURL = "https://yin-se.github.io/IStudyKotlin/"
languageCode = "zh-cn"
title = "Kotlin 学习笔记（可运行）"
theme = ""

[params]
  description = "记录 Kotlin 学习笔记"

[pagination]
pagerSize = 10

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
